#!/bin/bash

set -e
set -x

env

. /usr/share/mkapp/functions

prepare

for arch in $ARCH; do
  rm -rf ivy
  set_env $arch
  ant_build clean-all
  mkdir -p target/tar
  apt-get download libmica-gpio:$arch
  mv libmica-gpio*.deb target/tar/libmica-gpio.deb
  ant_build
  if [ "$PUBLISH" ]; then
    publish_ivy ivy
    cd target/tar
    rm libmica-gpio.deb
    dpkg-name *.deb
    publish_deb *.deb
    cd -
  fi

  if [ "$RELEASE" ]; then
    cd target
    APP=$(ls *.app)
    APP=${APP%.app}
    mv $APP.app ${APP}_${arch}.app
    zip ../${APP}_${arch}.zip ${APP}_${arch}.app
    cd -
    echo "::set-output name=APP_${arch}::${APP}_${arch}.zip"
  fi
done
